<?php

namespace AppBundle\Repository;

/**
 * BusinessreportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessreportRepository extends \Doctrine\ORM\EntityRepository
{

}
