<?php

namespace AppBundle\Repository;

/**
 * CashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashRepository extends \Doctrine\ORM\EntityRepository
{
}
