<?php

namespace AppBundle\Repository;

/**
 * ConsumeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumeLogRepository extends \Doctrine\ORM\EntityRepository
{
}
