<?php

namespace AppBundle\Repository;

/**
 * RechargeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RechargeLogRepository extends \Doctrine\ORM\EntityRepository
{
}
