<?php

namespace AppBundle\Repository;

/**
 * SharesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharesRepository extends \Doctrine\ORM\EntityRepository
{
}
