easy_admin:
    entities:
        Product:
            class: AppBundle\Entity\Product
            label: '商品'
            form:
                fields:
                    - { property: title, label: '名称' }
                    - { property: 'imageFile', label: '标题图片', type: 'vich_image' }
                    - { property: company, label: '公司' }
                    - { property: price, label: '价格' }
                    - { property: description, label: '商品详情', type: 'ckeditor' }
            list:
                title: "%%entity_label%%列表"
                fields:
                    - { property: title, label: '名称' }
                    - { property: 'titleImg', label: '标题图片', type: 'image', base_path: '%app.path.product_images%' }
                    - { property: company, label: '公司' }
                    - { property: price, label: '价格' }