easy_admin:
    entities:
        Product:
            class: AppBundle\Entity\Product
            label: '商品'
            form:
                fields:
                    - { property: title, label: '名称' }
                    - { property: titleImg, label: '标题图片' }
                    - { property: company, label: '公司' }
                    - { property: price, label: '价格' }
                    - { property: description, label: '商品详情' }
            list:
                title: "%%entity_label%%列表"
                fields:
                    - { property: title, label: '名称' }
                    - { property: titleImg, label: '标题图片' }
                    - { property: company, label: '公司' }
                    - { property: price, label: '价格' }
                    - { property: description, label: '商品详情' }