easy_admin:
    entities:
        Shares:
            class: AppBundle\Entity\Shares
            label: '分红'
            list:
                title: '分红记录'
                fields:
                    - { property: consume.amount, label: '消费金额' }
                    - { property: shares, label: '份数' }
                    - { property: bonus, label: '获得分红' }
                    - { property: consume.afterBonus, label: '累计分红' }
                    - { property: createdAt, label: '开始时间' }
                    - { property: consume.endAt, label: '结束时间' }
                    - { property: user, label: '用户' }